### ISSUE TITLE
Run through sharing to different sites/accounts

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Sharing#16]
Sharing will have to be on a publicly accessible site before any real testing can happen.

Also will need accounts suitable for dummy data on
- Facebook
- Twitter
- Pinterest
- Tumblr

as well as an email address that's okay for testing spam.

Install wherever as usual, and in SiteSettings check the boxes for sharing to different social sites.

Buttons should appear on site pages and item pages.

We're using the provided buttons and code, so most of the work will be handled by them. We just need to make sure we can get to their forms.

**Comment by mebrett** [comment]
Forms are loading fine for the most part.
Some issues: 
- Neither the tumblr nor facebook posts pulled an image. I know that both of these services sometimes don't do very well pulling images, but it's worthwhile to see what cues their code might be looking for because text only posts just don't do as well, in my experience.
- Email subject line is the item title and the site title smushed together without a space (EmmaJane Austen) and both subject and item url are enclosed with ' ' 
- Embed code doesn't work on any browser
- The buttons look wonky in Safari (lined up neatly in Firefox and Chrome)

![addthis_safari_20160209](https://cloud.githubusercontent.com/assets/2314070/12930306/876be580-cf45-11e5-9d3d-4e97841d9277.png)

**Comment by patrickmj** [comment]
On an installation with the develop branch of S, these are ready for another look, with the exception of the Safari issue, which I haven't looked at yet.
